### ISSUE TITLE
Can't compile on the network part, libc missing?

### ISSUE THREAD

**Issue by RajahLone** [th-otto/MagicOnLinux#2]
Sorry, tried to compiled under Xcode 26.1.1 after mkdir build && cd build && cmake -G Xcode ..

1) had to add missing define, though <netinet/in.h> is there.
#define IPPROTO_BEETPH 94
#define IPPROTO_COMP 108
#define IPPROTO_L2TP 115
#define IPPROTO_UDPLITE 136
#define IPPROTO_MPLS 137
#define IPPROTO_ETHERNET 143

2) evenif these adds, then errors in ethernet_linux.cpp on some missing functions. My guess is libc may be missing in some declarations.

**Comment by th-otto** [comment]
Should be fixed now. Can you please try again?

Note that i can't test this code on macOS at all. On linux, it uses the tun/tap devices. I don't know where such devices are available at all. Aranym uses the Berkeley packet filter instead, but this code was not ported yet to MagicOnLinux, and it requires a suid executable to be run on startup.

**Comment by RajahLone** [comment]
MagicOnLinux-PR -> "Build Succeeded" in Xcode 26. Thanks!

Still have a "-313 network unreachable" at boot, but I probably missed something when installing your magxnet archive. Will search later. No hurry. Thanks to Andreas and you and the German people, I have now an Atari setup that don't get crazy the fan of my macbook air. Testing my softwares will be less painful than on Aranym.

**Comment by th-otto** [comment]
The things you most likely have to adjust are:

- settings in the [ETH0] section of magiclinux.conf
- ip addresses in C:\GEMSYS\HOME\MAGX_RC.NET
- nameserver in C:\ETC\RESOLV.CON (or C:\etc\resolv.conf, if that is on a drive with long names)

For the last two, examples are in the magiclin.zip archive.

In those examples i use:
- 00:41:45:54:48:30 for the MAC of address of the emulated machine
- 192.168.1.7 for the IP of the emulated machine
- 192.168.1.2 for the IP of the host (your mac in this case)
- 192.168.1.1 for the IP of the gateway. On my machine, this is the IP of the internet router

The nameserver is also set to 192.168.1.1

If you have a working network on aranym already, you should be able to use the same setup. In Mint, there are most likely some calls to /bin/ifconfig and /bin/route either in mint.cnf, or in some script invoked from there. These are identical to the entries in `magx_rc.net`.

But as already noted, currently the BPF type interface from aranym is not implemented in MagicOnLinux. You'll need some tun/tap driver (which, IIRC, means some kernel module).

Also note that i couldn't get it to fully work yet. A `ping` works, but http or other services don't work yet.

**Comment by RajahLone** [comment]
Ah, a [ETH0] must be added to the existing magiclinux.conf. Done it by renaming the old one, creating a new at start. Then copy/paste.

At some point on macAranym, tun/tap was the mandatory part on the install. But it never worked for me. Will try again. Thanks again!
